"""Run manifest and provenance helpers for datastore product outputs."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any, Mapping


def utc_now_iso() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


@dataclass(frozen=True)
class ProductRecord:
    """One produced artifact record in a run manifest."""

    product_type: str
    path: str
    system: str | None = None
    run_id: str | None = None
    created_at: str = field(default_factory=utc_now_iso)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class RunManifest:
    """Manifest for products generated by one workflow run."""

    manifest_version: str = "1.0"
    created_at: str = field(default_factory=utc_now_iso)
    workflow: str = ""
    profile: str = ""
    system: str | None = None
    run_id: str | None = None
    products: list[ProductRecord] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["products"] = [asdict(record) for record in self.products]
        return payload

    @classmethod
    def from_dict(cls, payload: Mapping[str, Any]) -> "RunManifest":
        products_payload = payload.get("products") or []
        products = [
            ProductRecord(
                product_type=str(item.get("product_type", "")),
                path=str(item.get("path", "")),
                system=item.get("system"),
                run_id=item.get("run_id"),
                created_at=str(item.get("created_at", utc_now_iso())),
                metadata=dict(item.get("metadata") or {}),
            )
            for item in products_payload
            if isinstance(item, Mapping)
        ]

        return cls(
            manifest_version=str(payload.get("manifest_version", "1.0")),
            created_at=str(payload.get("created_at", utc_now_iso())),
            workflow=str(payload.get("workflow", "")),
            profile=str(payload.get("profile", "")),
            system=payload.get("system"),
            run_id=payload.get("run_id"),
            products=products,
            metadata=dict(payload.get("metadata") or {}),
        )


def load_manifest(path: Path | str) -> RunManifest:
    manifest_path = Path(path).expanduser().resolve()
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")
    payload = json.loads(manifest_path.read_text(encoding="utf-8"))
    return RunManifest.from_dict(payload)


def save_manifest(path: Path | str, manifest: RunManifest) -> Path:
    manifest_path = Path(path).expanduser().resolve()
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(
        json.dumps(manifest.to_dict(), indent=2, sort_keys=True, default=str),
        encoding="utf-8",
    )
    return manifest_path


def append_product_record(
    *,
    manifest_path: Path | str,
    record: ProductRecord,
    workflow: str | None = None,
    profile: str | None = None,
    system: str | None = None,
    run_id: str | None = None,
    metadata: Mapping[str, Any] | None = None,
) -> Path:
    path = Path(manifest_path).expanduser().resolve()

    if path.exists():
        manifest = load_manifest(path)
    else:
        manifest = RunManifest(
            workflow=workflow or "",
            profile=profile or "",
            system=system,
            run_id=run_id,
            metadata=dict(metadata or {}),
        )

    if workflow and not manifest.workflow:
        manifest.workflow = workflow
    if profile and not manifest.profile:
        manifest.profile = profile
    if system and not manifest.system:
        manifest.system = system
    if run_id and not manifest.run_id:
        manifest.run_id = run_id
    if metadata:
        manifest.metadata.update(dict(metadata))

    manifest.products.append(record)
    return save_manifest(path, manifest)


def build_store_metadata(
    *,
    product_type: str,
    system: str | None = None,
    run_id: str | None = None,
    source: str | None = None,
    workflow: str | None = None,
    profile: str | None = None,
    extra: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "product_type": product_type,
        "created_at": utc_now_iso(),
    }
    if system:
        payload["system"] = system
    if run_id:
        payload["run_id"] = run_id
    if source:
        payload["source"] = source
    if workflow:
        payload["workflow"] = workflow
    if profile:
        payload["profile"] = profile
    if extra:
        payload.update(dict(extra))
    return payload


__all__ = [
    "ProductRecord",
    "RunManifest",
    "append_product_record",
    "build_store_metadata",
    "load_manifest",
    "save_manifest",
    "utc_now_iso",
]
